server:
  port: 8084

spring:
  application:
    name: saga-service

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: saga-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.example.core.*"
        spring.json.value.default.type: "com.example.core.event.order.OrderCreatedEvent"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, metrics, info
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name:unknown}

logging:
  level:
    com.example.saga: DEBUG
    org.springframework.kafka: DEBUG
    org.springframework.transaction: DEBUG
    com.example.saga.consumerSaga: DEBUG