spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: saga-group             # Consumer group ??? ????
      auto-offset-reset: earliest      # ?????? ? ??????
      properties:
        spring.json.trusted.packages: "com.example.core.*"  # ?????????? ??????
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


# ????????? ??????????
server:
  port: 8082  # ?????????? ???? ??? ???? (? order ????? ???? 8081 ? ?.?.)

logging:
  level:
    com.example.saga: DEBUG
    org.springframework.kafka: INFO